var app=angular.module('myapp',[]);
app.controller('buttonCtrl',function($scope){
      $scope.text="";
      $scope.input1=function(){
        $scope.text=$scope.text+"1";
      }
      $scope.input2=function(){
        $scope.text=$scope.text+"2";
      }
      $scope.input3=function(){
        $scope.text=$scope.text+"3";
      }
      $scope.input4=function(){
        $scope.text=$scope.text+"4";
      }
      $scope.input5=function(){
        $scope.text=$scope.text+"5";
      }
      $scope.input6=function(){
        $scope.text=$scope.text+"6";
      }
      $scope.input7=function(){
        $scope.text=$scope.text+"7";
      }
      $scope.input8=function(){
        $scope.text=$scope.text+"8";
      }
      $scope.input9=function(){
        $scope.text=$scope.text+"9";
      }
      $scope.input0=function(){
        $scope.text=$scope.text+"0";
      }
      $scope.add=function(){
        $scope.text=$scope.text+"+";
      }
      $scope.minus=function(){
        $scope.text=$scope.text+"-";
      }
      $scope.multiply=function(){
        $scope.text=$scope.text+"*";
      }
      $scope.divide=function(){
        $scope.text=$scope.text+"/";
      }
      $scope.equal=function(){
        $scope.text=eval($scope.text);
      }
      $scope.leftBracket=function(){
        $scope.text=$scope.text+"(";
      }
      $scope.rightBracket=function(){
        $scope.text=$scope.text+")";
      }
      $scope.dot=function(){
        $scope.text=$scope.text+".";
      }
      $scope.back=function(){
        $scope.text=$scope.text.substring(0,$scope.text.length-1);
      }
      $scope.clear=function(){
        $scope.text="";
      }
});
